server:
  port: 8100
  forward-headers-strategy: framework
  servlet:
    context-path: "/schedule"

spring:
  application:
    name: schedule-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/conference"

app:
  openapi:
    version: "@project.version@"
    well-known-oidc-configuration-url: "http://localhost:8080/realms/conference/.well-known/openid-configuration"

  security:
    unprotected-paths:
      - "/api-docs**"
      - "/api-docs/**"
      - "/swagger-ui**"
      - "/swagger-ui/**"
      - "/actuator/health"

springdoc:
  api-docs:
    enabled: true
    path: "/api-docs"
  swagger-ui:
    enabled: true
    path: "/swagger-ui"
    tags-sorter: "alpha"
    operations-sorter: "alpha"
    oauth:
      client-id: "public"
      use-pkce-with-authorization-code-grant: true
      scopes:
        - "openid"
        - "profile"
        - "email"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
